server:
  port: 8190
  servlet:
    context-path: ""
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${jdbcUrl}
    username: ${login}
    password: ${password}
  flyway:
    enabled: true
    locations: classpath:/db/migration
#  jpa:
#    hibernate:
#      ddl-auto: create-drop

app-path: /api/v1/
key: secretKey

