DROP TABLE IF EXISTS POSTS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS TAGS;

CREATE TABLE ROLES
(
    ID   SERIAL PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE,
    AUTHORITY VARCHAR(255)
);

CREATE TABLE USERS
(
    ID         SERIAL PRIMARY KEY,
    USERNAME   VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD   VARCHAR(255) NOT NULL,
    EMAIL      VARCHAR(255) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP,
    CHANGED_AT TIMESTAMP,
    ROLE       INTEGER
        CONSTRAINT FK_USER_ID_ROLE_ID_RELATION
            REFERENCES ROLES,
    ENABLED    BOOLEAN
);

CREATE TABLE TAGS
(
    ID   SERIAL PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE
);

CREATE TABLE POSTS
(
    ID         SERIAL PRIMARY KEY,
    TITLE      VARCHAR(255),
    TEXT       VARCHAR(255),
    CREATED_AT TIMESTAMP,
    USER_ID    INTEGER
        CONSTRAINT FK_POST_ID_USER_ID_RELATION
            REFERENCES USERS
);

CREATE TABLE POSTS_TAGS
(
    POST_ID INTEGER,
    TAG_ID  INTEGER,
    PRIMARY KEY (POST_ID, TAG_ID),
    FOREIGN KEY (POST_ID) REFERENCES POSTS (ID),
    FOREIGN KEY (TAG_ID) REFERENCES TAGS (ID)
)